In [3]:
# Bag OF Words IMplementation
import pandas as pd
df=pd.read_csv('./spam.csv',encoding="ISO-8859-1")
# instead of comma it will use tab seprated value for reading

In [4]:
df.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [5]:
df.columns = df.columns.str.strip()  # Removes extra spaces or tabs
df.drop(['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], axis=1,inplace=True)  #whwn we write inplace it does'nt return anything

In [6]:
df.columns = df.columns.str.strip()  # Removes spaces or tabs

df.rename(columns={'v1':'label','v2':'message'},inplace=True)


In [7]:
df.head()

messages=df

messages

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [8]:
# Data cleaning and preprocessing
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ddurande/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [9]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

ps=PorterStemmer()

In [10]:
corpous=[]

for i in range(0,len(messages)):
    review=re.sub('^a-zA-Z',' ',messages['message'][i]) #inside messagges in every message apply if other than a to z or A to Z occured replace with ' 'bag_of_words.ipynb
    review=review.lower()
    # print(review) we need list
    review=review.split()
    # print(review) we got list of reviews
    # now apply steming on each word which is not stopword
    review=[ps.stem(word) for word in review if  not word in stopwords.words('English')]
    review=' '.join(review)
    # print(review)
    corpous.append(review)

In [11]:
corpous

['go jurong point, crazy.. avail bugi n great world la e buffet... cine got amor wat...',
 'ok lar... joke wif u oni...',
 "free entri 2 wkli comp win fa cup final tkt 21st may 2005. text fa 87121 receiv entri question(std txt rate)t&c' appli 08452810075over18'",
 'u dun say earli hor... u c alreadi say...',
 'nah think goe usf, live around though',
 "freemsg hey darl 3 week' word back! i'd like fun still? tb ok! xxx std chg send, å£1.50 rcv",
 'even brother like speak me. treat like aid patent.',
 "per request 'mell mell (oru minnaminungint nurungu vettam)' set callertun callers. press *9 copi friend callertun",
 'winner!! valu network custom select receivea å£900 prize reward! claim call 09061701461. claim code kl341. valid 12 hour only.',
 'mobil 11 month more? u r entitl updat latest colour mobil camera free! call mobil updat co free 08002986030',
 "i'm gonna home soon want talk stuff anymor tonight, k? i'v cri enough today.",
 'six chanc win cash! 100 20,000 pound txt> csh11 send 

In [12]:
# now apply bag of words model
# !pip install scikit-learn
from sklearn.feature_extraction.text import CountVectorizer
# cv=CountVectorizer(max_features=50)  # here focused on max_feature parameter this is Normal bag of words
cv=CountVectorizer(max_features=50,binary=True)  # here focused on max_feature parameter: this is binary BOW


In [13]:
X=cv.fit_transform(corpous).toarray()

In [14]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(5572, 50))

In [15]:
X.shape

(5572, 50)

In [16]:
cv.vocabulary_   #give top 50 words how many times occured this are indexes which occured most

{'go': np.int64(10),
 'got': np.int64(12),
 'ok': np.int64(29),
 'free': np.int64(8),
 'text': np.int64(41),
 'txt': np.int64(46),
 'say': np.int64(34),
 'think': np.int64(43),
 'back': np.int64(1),
 'like': np.int64(19),
 'still': np.int64(37),
 'send': np.int64(36),
 'me': np.int64(25),
 'call': np.int64(2),
 'co': np.int64(3),
 'home': np.int64(15),
 'want': np.int64(48),
 'today': np.int64(45),
 'day': np.int64(6),
 'repli': np.int64(33),
 'take': np.int64(39),
 'make': np.int64(24),
 'dont': np.int64(7),
 'ur': np.int64(47),
 'da': np.int64(5),
 'lor': np.int64(21),
 'get': np.int64(9),
 'know': np.int64(17),
 'love': np.int64(22),
 'now': np.int64(28),
 'll': np.int64(20),
 'that': np.int64(42),
 'you': np.int64(49),
 'tell': np.int64(40),
 'pleas': np.int64(32),
 'time': np.int64(44),
 'see': np.int64(35),
 'need': np.int64(26),
 'lt': np.int64(23),
 'gt': np.int64(13),
 'ask': np.int64(0),
 'it': np.int64(16),
 'new': np.int64(27),
 'later': np.int64(18),
 'good': np.int64(11),

In [17]:
# for using N gram
cv=CountVectorizer(max_features=500,binary=True,ngram_range=(2,2))
# for better accuracy we can increase range of n gram
X=cv.fit_transform(corpous).toarray()
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(5572, 500))

In [18]:
cv.vocabulary_   # we will get two words also

{'free entri': np.int64(152),
 'rate appli': np.int64(347),
 'per request': np.int64(324),
 '900 prize': np.int64(45),
 'claim call': np.int64(97),
 'claim code': np.int64(98),
 'entitl updat': np.int64(139),
 'updat latest': np.int64(438),
 'latest colour': np.int64(234),
 'free call': np.int64(150),
 'call mobil': np.int64(75),
 'mobil updat': np.int64(284),
 'chanc win': np.int64(93),
 'repli hl': np.int64(355),
 'txt word': np.int64(434),
 'dont miss': np.int64(130),
 'let know': np.int64(239),
 'feel like': np.int64(144),
 'mobil charg': np.int64(281),
 'go home': np.int64(171),
 'anyth lor': np.int64(49),
 'need you': np.int64(294),
 'mobil free': np.int64(282),
 'pleas call': np.int64(333),
 'call 08000930705': np.int64(65),
 'deliveri tomorrow': np.int64(125),
 'lt gt': np.int64(264),
 'miss call': np.int64(276),
 'want go': np.int64(467),
 'first time': np.int64(147),
 'like lt': np.int64(243),
 'sms ac': np.int64(382),
 'yours call': np.int64(497),
 'bx420 ip4': np.int64(64),

In [19]:
messages=df

In [21]:
from nltk.stem import WordNetLemmatizer

lm=WordNetLemmatizer()

In [25]:
# Performing tfidf using lemmetization
corpous=[]
for i in range(0,len(messages)):
    review=re.sub('^a-zA-Z',' ',messages['message'][i])
    review=review.lower()
    review=review.split()
    review=[lm.lemmatize(word) for word in review if word not in stopwords.words('ENglish')]
    review=' '.join(review)
    corpous.append(review)


In [26]:
corpous

['go jurong point, crazy.. available bugis n great world la e buffet... cine got amore wat...',
 'ok lar... joking wif u oni...',
 "free entry 2 wkly comp win fa cup final tkts 21st may 2005. text fa 87121 receive entry question(std txt rate)t&c's apply 08452810075over18's",
 'u dun say early hor... u c already say...',
 'nah think go usf, life around though',
 "freemsg hey darling 3 week's word back! i'd like fun still? tb ok! xxx std chgs send, å£1.50 rcv",
 'even brother like speak me. treat like aid patent.',
 "per request 'melle melle (oru minnaminunginte nurungu vettam)' set callertune callers. press *9 copy friend callertune",
 'winner!! valued network customer selected receivea å£900 prize reward! claim call 09061701461. claim code kl341. valid 12 hour only.',
 'mobile 11 month more? u r entitled update latest colour mobile camera free! call mobile update co free 08002986030',
 "i'm gonna home soon want talk stuff anymore tonight, k? i've cried enough today.",
 'six chance win 

In [28]:
from sklearn.feature_extraction.text import TfidfVectorizer

vc=TfidfVectorizer(max_features=100)
X=vc.fit_transform(corpous).toarray()

In [30]:
import numpy as np
np.set_printoptions(edgeitems=30,linewidth=10000,
                    formatter=dict(float=lambda x:'%.3g' % x))

In [31]:
X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.436, 0, 0, 0.461, 0.543, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.549, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.454, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0.471, 0, 0, 0, 0, 0, 0, 0, 0, 0.489, 0, 0, 0, 0, 0, 0, 0.577, 0, 0, 0, 0, 0, 0],
       [0.464, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.487, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.572, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [32]:
# use N Gram
vc=TfidfVectorizer(max_features=100,ngram_range=(2,2))
X=vc.fit_transform(corpous).toarray()

In [36]:
vc.vocabulary_

{'free entry': np.int64(33),
 'claim call': np.int64(18),
 'free call': np.int64(32),
 'chance win': np.int64(17),
 'txt word': np.int64(87),
 'we re': np.int64(98),
 'let know': np.int64(54),
 'please call': np.int64(66),
 'call 08000930705': np.int64(9),
 'lt gt': np.int64(59),
 'want go': np.int64(95),
 'like lt': np.int64(55),
 'sorry ll': np.int64(79),
 'll call': np.int64(57),
 'call later': np.int64(11),
 'ur awarded': np.int64(89),
 'hi hi': np.int64(48),
 'call customer': np.int64(10),
 'customer service': np.int64(24),
 'guaranteed 1000': np.int64(42),
 '1000 cash': np.int64(0),
 'trying contact': np.int64(84),
 'contact you': np.int64(23),
 'draw show': np.int64(29),
 'prize guaranteed': np.int64(71),
 'guaranteed call': np.int64(43),
 'valid 12hrs': np.int64(93),
 'selected receive': np.int64(75),
 'account statement': np.int64(6),
 'identifier code': np.int64(50),
 'urgent mobile': np.int64(92),
 'caller prize': np.int64(14),
 'wat time': np.int64(96),
 'ur mob': np.int64(